<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GARIMA7LT" name="virginia_regression._06_Create_EPP_31" tests="8" failures="1" timestamp="14 Jun 2017 20:57:55 GMT" time="314.842" errors="0">
  <testcase name="_2_navigate_to_eCashURL" time="7.724" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_6_businessdatebacktoOriginal" time="6.231" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_1_admin_login" time="14.515" classname="virginia_regression._06_Create_EPP_31">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at virginia_regression._06_Create_EPP_31._1_admin_login(_06_Create_EPP_31.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- _1_admin_login -->
  <testcase name="_8_logout_store" time="1.346" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_3_teller_login" time="39.184" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_4_new_4_PRAs_Creation" time="176.599" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_7_logout_admin" time="5.239" classname="virginia_regression._06_Create_EPP_31"/>
  <testcase name="_5_EPP_ON_BEFORE_AFTER_Origination_DueDate" time="64.004" classname="virginia_regression._06_Create_EPP_31"/>
</testsuite> <!-- virginia_regression._06_Create_EPP_31 -->
