<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GARIMA7LT" name="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol" tests="9" failures="3" timestamp="3 Apr 2017 13:56:18 GMT" time="125.045" errors="0">
  <testcase name="newLOCs_Creation" time="51.424" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.newLOCs_Creation(_7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- newLOCs_Creation -->
  <testcase name="RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_On_10days" time="2.772" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_On_10days(_7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.java:419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_On_10days -->
  <testcase name="RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_within_10days" time="1.814" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_within_10days(_7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_within_10days -->
  <testcase name="StroreLogin" time="10.286" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
  <testcase name="Businessdatechange" time="14.843" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
  <testcase name="Navigate_to_eCashURL" time="11.626" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
  <testcase name="log_out" time="4.475" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
  <testcase name="RapidPay_Unenrollment_Reenrollment_DueDate_Recalculation_Before_10days" time="16.817" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
  <testcase name="BusinessDatebacktoOriginal" time="10.988" classname="Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol"/>
</testsuite> <!-- Virginia_Regression._7_Verify_RPDueDateRecalc_Post_RPUnenrolEnrol -->
